--- 
abstract: Safety ServerPages syntax
author: 
  - cho45 <cho45@lowreal.net>
build_requires: 
  Test::Base: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Text-MicroMason-SafeServerPages
no_index: 
  directory: 
    - inc
    - t
requires: 
  Text::MicroMason: 0
version: 0.03
